In [1]:
import pandas as pd

In [2]:
df=pd.read_csv("gk_qna_dataset.csv")
df.head(5)

                            question  answer
0   What is the capital of "France"?   Paris
1  What is the capital of "Germany"?  Berlin
2    What is the capital of "Italy"?    Rome
3    What is the capital of "Spain"?  Madrid
4    What is the capital of "Japan"?   Tokyo

In [3]:
df['question'][0]

'What is the capital of "France"?'

tokenization

In [5]:
import re 

def tokenize(text):
       #lowercase 
       text=text.lower()


       # remove quotes 
       text=re.sub(r"[\'\"]", "", text)


       # remove all punctuations 
       text=re.sub(r"[^a-z0-9\s]", "", text)
       text=re.sub(r"\s+", " ", text)

       #remove extra space
       tokens=text.split()


       return tokens

In [6]:
print(tokenize(df['question'][0]))

['what', 'is', 'the', 'capital', 'of', 'france']

In [7]:
vocab={'UNK': 0}

In [8]:
def build_vocab(row):
       print(row['question'],row['answer'])

       tokenized_question = tokenize(row['question'])
       tokenized_answer = tokenize(row['answer'])
       print(tokenized_question,tokenized_answer)
       merged_tokens=tokenized_question+tokenized_answer
       for token in merged_tokens:
              if token not in vocab:
                     vocab[token]=len(vocab)

In [9]:
df.apply(build_vocab,axis=1)

What is the capital of "France"? Paris
['what', 'is', 'the', 'capital', 'of', 'france'] ['paris']
What is the capital of "Germany"? Berlin
['what', 'is', 'the', 'capital', 'of', 'germany'] ['berlin']
What is the capital of "Italy"? Rome
['what', 'is', 'the', 'capital', 'of', 'italy'] ['rome']
What is the capital of "Spain"? Madrid
['what', 'is', 'the', 'capital', 'of', 'spain'] ['madrid']
What is the capital of "Japan"? Tokyo
['what', 'is', 'the', 'capital', 'of', 'japan'] ['tokyo']
What is the capital of "Canada"? Ottawa
['what', 'is', 'the', 'capital', 'of', 'canada'] ['ottawa']
What is the capital of "Brazil"? Brasilia
['what', 'is', 'the', 'capital', 'of', 'brazil'] ['brasilia']
What is the capital of "Australia"? Canberra
['what', 'is', 'the', 'capital', 'of', 'australia'] ['canberra']
What is the capital of "India"? New Delhi
['what', 'is', 'the', 'capital', 'of', 'india'] ['new', 'delhi']
What is the capital of "China"? Beijing
['what', 'is', 'the', 'capital', 'of', 'china'] ['beijing']
What is the capital of "Russia"? Moscow
['what', 'is', 'the', 'capital', 'of', 'russia'] ['moscow']
What is the capital of "United States"? Washington DC
['what', 'is', 'the', 'capital', 'of', 'united', 'states'] ['washington', 'dc']
What is the capital of "Mexico"? Mexico City
['what', 'is', 'the', 'capital', 'of', 'mexico'] ['mexico', 'city']
What is the capital of "Egypt"? Cairo
['what', 'is', 'the', 'capital', 'of', 'egypt'] ['cairo']
What is the capital of "Turkey"? Ankara
['what', 'is', 'the', 'capital', 'of', 'turkey'] ['ankara']
What is the capital of "Argentina"? Buenos Aires
['what', 'is', 'the', 'capital', 'of', 'argentina'] ['buenos', 'aires']
What is the capital of "South Korea"? Seoul
['what', 'is', 'the', 'capital', 'of', 'south', 'korea'] ['seoul']
What is the capital of "Indonesia"? Jakarta
['what', 'is', 'the', 'capital', 'of', 'indonesia'] ['jakarta']
What is the capital of "Pakistan"? Islamabad
['what', 'is', 'the', 'capital', 'of', 'pakistan'] ['islamabad']
What is the capital of "Bangladesh"? Dhaka
['what', 'is', 'the', 'capital', 'of', 'bangladesh'] ['dhaka']
What is the capital of "Nepal"? Kathmandu
['what', 'is', 'the', 'capital', 'of', 'nepal'] ['kathmandu']
What is the capital of "Sri Lanka"? Colombo
['what', 'is', 'the', 'capital', 'of', 'sri', 'lanka'] ['colombo']
What is the capital of "Thailand"? Bangkok
['what', 'is', 'the', 'capital', 'of', 'thailand'] ['bangkok']
What is the capital of "Malaysia"? Kuala Lumpur
['what', 'is', 'the', 'capital', 'of', 'malaysia'] ['kuala', 'lumpur']
What is the capital of "Vietnam"? Hanoi
['what', 'is', 'the', 'capital', 'of', 'vietnam'] ['hanoi']
What is the capital of "UAE"? Abu Dhabi
['what', 'is', 'the', 'capital', 'of', 'uae'] ['abu', 'dhabi']
What is the capital of "Iran"? Tehran
['what', 'is', 'the', 'capital', 'of', 'iran'] ['tehran']
What is the capital of "Iraq"? Baghdad
['what', 'is', 'the', 'capital', 'of', 'iraq'] ['baghdad']
What is the capital of "Saudi Arabia"? Riyadh
['what', 'is', 'the', 'capital', 'of', 'saudi', 'arabia'] ['riyadh']
What is the capital of "Nigeria"? Abuja
['what', 'is', 'the', 'capital', 'of', 'nigeria'] ['abuja']
What is the capital of "Kenya"? Nairobi
['what', 'is', 'the', 'capital', 'of', 'kenya'] ['nairobi']
What is the capital of "Chile"? Santiago
['what', 'is', 'the', 'capital', 'of', 'chile'] ['santiago']
Who discovered 'gravity'? Isaac Newton
['who', 'discovered', 'gravity'] ['isaac', 'newton']
Who invented the 'telephone'? Alexander Graham Bell
['who', 'invented', 'the', 'telephone'] ['alexander', 'graham', 'bell']
What is 'H2O' commonly called? Water
['what', 'is', 'h2o', 'commonly', 'called'] ['water']
Which gas do plants absorb? Carbon dioxide
['which', 'gas', 'do', 'plants', 'absorb'] ['carbon', 'dioxide']
Which planet is known as the 'Red Planet'? Mars
['which', 'planet', 'is', 'known', 'as', 'the', 'red', 'planet'] ['mars']
Who painted the 'Mona Lisa'? Leonardo da Vinci
['who', 'painted', 'the', 'mona', 'lisa'] ['leonardo', 'da', 'vinci']
What is the largest ocean? Pacific Ocean
['what', 'is', 'the', 'largest', 'ocean'] ['pacific', 'ocean']
Who developed the 'theory of relativity'? Albert Einstein
['who', 'developed', 'the', 'theory', 'of', 'relativity'] ['albert', 'einstein']
What is 'AI' short for? Artificial Intelligence
['what', 'is', 'ai', 'short', 'for'] ['artificial', 'intelligence']
What is 'ML' short for? Machine Learning
['what', 'is', 'ml', 'short', 'for'] ['machine', 'learning']
What is 'NLP' short for? Natural Language Processing
['what', 'is', 'nlp', 'short', 'for'] ['natural', 'language', 'processing']
What does 'CPU' stand for? Central Processing Unit
['what', 'does', 'cpu', 'stand', 'for'] ['central', 'processing', 'unit']
What is 'RAM'? Computer memory
['what', 'is', 'ram'] ['computer', 'memory']
What does 'GPU' stand for? Graphics Processing Unit
['what', 'does', 'gpu', 'stand', 'for'] ['graphics', 'processing', 'unit']
What is a 'URL'? Web address
['what', 'is', 'a', 'url'] ['web', 'address']
What does 'HTTP' stand for? HyperText Transfer Protocol
['what', 'does', 'http', 'stand', 'for'] ['hypertext', 'transfer', 'protocol']
What is 'JSON' used for? Data exchange
['what', 'is', 'json', 'used', 'for'] ['data', 'exchange']
What is 'SQL'? Database query language
['what', 'is', 'sql'] ['database', 'query', 'language']
What does 'API' mean? Application Programming Interface
['what', 'does', 'api', 'mean'] ['application', 'programming', 'interface']
Who invented the 'light bulb'? Thomas Edison
['who', 'invented', 'the', 'light', 'bulb'] ['thomas', 'edison']
Who invented the 'airplane'? Wright Brothers
['who', 'invented', 'the', 'airplane'] ['wright', 'brothers']
Who discovered 'penicillin'? Alexander Fleming
['who', 'discovered', 'penicillin'] ['alexander', 'fleming']
Who wrote 'Hamlet'? William Shakespeare
['who', 'wrote', 'hamlet'] ['william', 'shakespeare']
Who wrote 'Harry Potter'? J K Rowling
['who', 'wrote', 'harry', 'potter'] ['j', 'k', 'rowling']
Which country is known as the 'Land of Rising Sun'? Japan
['which', 'country', 'is', 'known', 'as', 'the', 'land', 'of', 'rising', 'sun'] ['japan']
Which animal is called the 'King of Jungle'? Lion
['which', 'animal', 'is', 'called', 'the', 'king', 'of', 'jungle'] ['lion']
Which animal is the largest on Earth? Blue Whale
['which', 'animal', 'is', 'the', 'largest', 'on', 'earth'] ['blue', 'whale']
Which bird cannot fly? Ostrich
['which', 'bird', 'cannot', 'fly'] ['ostrich']
Which animal is known for loyalty? Dog
['which', 'animal', 'is', 'known', 'for', 'loyalty'] ['dog']
Which fruit is typically red? Apple
['which', 'fruit', 'is', 'typically', 'red'] ['apple']
Which fruit is yellow? Banana
['which', 'fruit', 'is', 'yellow'] ['banana']
Which organ pumps blood? Heart
['which', 'organ', 'pumps', 'blood'] ['heart']
Which gas do humans breathe? Oxygen
['which', 'gas', 'do', 'humans', 'breathe'] ['oxygen']
Which metal is liquid at room temperature? Mercury
['which', 'metal', 'is', 'liquid', 'at', 'room', 'temperature'] ['mercury']
Which instrument measures temperature? Thermometer
['which', 'instrument', 'measures', 'temperature'] ['thermometer']
Which instrument measures pressure? Barometer
['which', 'instrument', 'measures', 'pressure'] ['barometer']
What is the main language of Brazil? Portuguese
['what', 'is', 'the', 'main', 'language', 'of', 'brazil'] ['portuguese']
What is the main language of Spain? Spanish
['what', 'is', 'the', 'main', 'language', 'of', 'spain'] ['spanish']
What is the main religion in Saudi Arabia? Islam
['what', 'is', 'the', 'main', 'religion', 'in', 'saudi', 'arabia'] ['islam']
What is the national animal of Bangladesh? Royal Bengal Tiger
['what', 'is', 'the', 'national', 'animal', 'of', 'bangladesh'] ['royal', 'bengal', 'tiger']
Quick question: "Who invented the 'light bulb'"? Thomas Edison
['quick', 'question', 'who', 'invented', 'the', 'light', 'bulb'] ['thomas', 'edison']
"Who discovered 'penicillin'" — do you know? Alexander Fleming
['who', 'discovered', 'penicillin', 'do', 'you', 'know'] ['alexander', 'fleming']
Do you know, "What is the largest ocean"? Pacific Ocean
['do', 'you', 'know', 'what', 'is', 'the', 'largest', 'ocean'] ['pacific', 'ocean']
I was wondering, "What is a 'URL'"? Web address
['i', 'was', 'wondering', 'what', 'is', 'a', 'url'] ['web', 'address']
Hey, what about this: "Which instrument measures pressure"? Barometer
['hey', 'what', 'about', 'this', 'which', 'instrument', 'measures', 'pressure'] ['barometer']
"Who invented the 'telephone'" — do you know? Alexander Graham Bell
['who', 'invented', 'the', 'telephone', 'do', 'you', 'know'] ['alexander', 'graham', 'bell']
I was wondering, "Who invented the 'light bulb'"? Thomas Edison
['i', 'was', 'wondering', 'who', 'invented', 'the', 'light', 'bulb'] ['thomas', 'edison']
Quick question: "What is the main language of Spain"? Spanish
['quick', 'question', 'what', 'is', 'the', 'main', 'language', 'of', 'spain'] ['spanish']
Hey, what about this: "What is a 'URL'"? Web address
['hey', 'what', 'about', 'this', 'what', 'is', 'a', 'url'] ['web', 'address']
I was wondering, "Which gas do humans breathe"? Oxygen
['i', 'was', 'wondering', 'which', 'gas', 'do', 'humans', 'breathe'] ['oxygen']
I was wondering, "Which organ pumps blood"? Heart
['i', 'was', 'wondering', 'which', 'organ', 'pumps', 'blood'] ['heart']
Hey, what about this: "What is the largest ocean"? Pacific Ocean
['hey', 'what', 'about', 'this', 'what', 'is', 'the', 'largest', 'ocean'] ['pacific', 'ocean']
Do you know, "Who invented the 'telephone'"? Alexander Graham Bell
['do', 'you', 'know', 'who', 'invented', 'the', 'telephone'] ['alexander', 'graham', 'bell']
Quick question: "Who wrote 'Hamlet'"? William Shakespeare
['quick', 'question', 'who', 'wrote', 'hamlet'] ['william', 'shakespeare']
"Which instrument measures pressure" — do you know? Barometer
['which', 'instrument', 'measures', 'pressure', 'do', 'you', 'know'] ['barometer']
Can you tell me, "What is the national animal of Bangladesh"? Royal Bengal Tiger
['can', 'you', 'tell', 'me', 'what', 'is', 'the', 'national', 'animal', 'of', 'bangladesh'] ['royal', 'bengal', 'tiger']
Quick question: "What is the main language of Brazil"? Portuguese
['quick', 'question', 'what', 'is', 'the', 'main', 'language', 'of', 'brazil'] ['portuguese']
Hey, what about this: "Who developed the 'theory of relativity'"? Albert Einstein
['hey', 'what', 'about', 'this', 'who', 'developed', 'the', 'theory', 'of', 'relativity'] ['albert', 'einstein']
Hey, what about this: "What is 'AI' short for"? Artificial Intelligence
['hey', 'what', 'about', 'this', 'what', 'is', 'ai', 'short', 'for'] ['artificial', 'intelligence']
I was wondering, "Which animal is known for loyalty"? Dog
['i', 'was', 'wondering', 'which', 'animal', 'is', 'known', 'for', 'loyalty'] ['dog']
Do you know, "What is a 'URL'"? Web address
['do', 'you', 'know', 'what', 'is', 'a', 'url'] ['web', 'address']
Quick question: "Which gas do plants absorb"? Carbon dioxide
['quick', 'question', 'which', 'gas', 'do', 'plants', 'absorb'] ['carbon', 'dioxide']
I was wondering, "Who invented the 'telephone'"? Alexander Graham Bell
['i', 'was', 'wondering', 'who', 'invented', 'the', 'telephone'] ['alexander', 'graham', 'bell']
Do you know, "Which fruit is yellow"? Banana
['do', 'you', 'know', 'which', 'fruit', 'is', 'yellow'] ['banana']
Can you tell me, "Which planet is known as the 'Red Planet'"? Mars
['can', 'you', 'tell', 'me', 'which', 'planet', 'is', 'known', 'as', 'the', 'red', 'planet'] ['mars']
Do you know, "Which gas do plants absorb"? Carbon dioxide
['do', 'you', 'know', 'which', 'gas', 'do', 'plants', 'absorb'] ['carbon', 'dioxide']
Can you tell me, "What does 'CPU' stand for"? Central Processing Unit
['can', 'you', 'tell', 'me', 'what', 'does', 'cpu', 'stand', 'for'] ['central', 'processing', 'unit']
Hey, what about this: "Who wrote 'Harry Potter'"? J K Rowling
['hey', 'what', 'about', 'this', 'who', 'wrote', 'harry', 'potter'] ['j', 'k', 'rowling']
Do you know, "What does 'GPU' stand for"? Graphics Processing Unit
['do', 'you', 'know', 'what', 'does', 'gpu', 'stand', 'for'] ['graphics', 'processing', 'unit']
Quick question: "Which gas do humans breathe"? Oxygen
['quick', 'question', 'which', 'gas', 'do', 'humans', 'breathe'] ['oxygen']
I was wondering, "What is 'RAM'"? Computer memory
['i', 'was', 'wondering', 'what', 'is', 'ram'] ['computer', 'memory']
Can you tell me, "What is the largest ocean"? Pacific Ocean
['can', 'you', 'tell', 'me', 'what', 'is', 'the', 'largest', 'ocean'] ['pacific', 'ocean']
Quick question: "Which metal is liquid at room temperature"? Mercury
['quick', 'question', 'which', 'metal', 'is', 'liquid', 'at', 'room', 'temperature'] ['mercury']
Quick question: "What is 'ML' short for"? Machine Learning
['quick', 'question', 'what', 'is', 'ml', 'short', 'for'] ['machine', 'learning']
Hey, what about this: "Which fruit is yellow"? Banana
['hey', 'what', 'about', 'this', 'which', 'fruit', 'is', 'yellow'] ['banana']
Hey, what about this: "Which instrument measures temperature"? Thermometer
['hey', 'what', 'about', 'this', 'which', 'instrument', 'measures', 'temperature'] ['thermometer']
"Which animal is the largest on Earth" — do you know? Blue Whale
['which', 'animal', 'is', 'the', 'largest', 'on', 'earth', 'do', 'you', 'know'] ['blue', 'whale']
"What is the largest ocean" — do you know? Pacific Ocean
['what', 'is', 'the', 'largest', 'ocean', 'do', 'you', 'know'] ['pacific', 'ocean']
"Which organ pumps blood" — do you know? Heart
['which', 'organ', 'pumps', 'blood', 'do', 'you', 'know'] ['heart']
Can you tell me, "Who wrote 'Hamlet'"? William Shakespeare
['can', 'you', 'tell', 'me', 'who', 'wrote', 'hamlet'] ['william', 'shakespeare']
Do you know, "What is the main language of Brazil"? Portuguese
['do', 'you', 'know', 'what', 'is', 'the', 'main', 'language', 'of', 'brazil'] ['portuguese']
"Who painted the 'Mona Lisa'" — do you know? Leonardo da Vinci
['who', 'painted', 'the', 'mona', 'lisa', 'do', 'you', 'know'] ['leonardo', 'da', 'vinci']
Do you know, "Which country is known as the 'Land of Rising Sun'"? Japan
['do', 'you', 'know', 'which', 'country', 'is', 'known', 'as', 'the', 'land', 'of', 'rising', 'sun'] ['japan']
Quick question: "Which animal is called the 'King of Jungle'"? Lion
['quick', 'question', 'which', 'animal', 'is', 'called', 'the', 'king', 'of', 'jungle'] ['lion']
Can you tell me, "Which fruit is yellow"? Banana
['can', 'you', 'tell', 'me', 'which', 'fruit', 'is', 'yellow'] ['banana']
Can you tell me, "Who invented the 'light bulb'"? Thomas Edison
['can', 'you', 'tell', 'me', 'who', 'invented', 'the', 'light', 'bulb'] ['thomas', 'edison']
Quick question: "Who discovered 'penicillin'"? Alexander Fleming
['quick', 'question', 'who', 'discovered', 'penicillin'] ['alexander', 'fleming']
I was wondering, "Who wrote 'Harry Potter'"? J K Rowling
['i', 'was', 'wondering', 'who', 'wrote', 'harry', 'potter'] ['j', 'k', 'rowling']
"What is the national animal of Bangladesh" — do you know? Royal Bengal Tiger
['what', 'is', 'the', 'national', 'animal', 'of', 'bangladesh', 'do', 'you', 'know'] ['royal', 'bengal', 'tiger']
Hey, what about this: "Which gas do plants absorb"? Carbon dioxide
['hey', 'what', 'about', 'this', 'which', 'gas', 'do', 'plants', 'absorb'] ['carbon', 'dioxide']
I was wondering, "What is 'JSON' used for"? Data exchange
['i', 'was', 'wondering', 'what', 'is', 'json', 'used', 'for'] ['data', 'exchange']
Can you tell me, "Who discovered 'gravity'"? Isaac Newton
['can', 'you', 'tell', 'me', 'who', 'discovered', 'gravity'] ['isaac', 'newton']
I was wondering, "Who invented the 'airplane'"? Wright Brothers
['i', 'was', 'wondering', 'who', 'invented', 'the', 'airplane'] ['wright', 'brothers']
Do you know, "Who invented the 'light bulb'"? Thomas Edison
['do', 'you', 'know', 'who', 'invented', 'the', 'light', 'bulb'] ['thomas', 'edison']
Can you tell me, "Which gas do humans breathe"? Oxygen
['can', 'you', 'tell', 'me', 'which', 'gas', 'do', 'humans', 'breathe'] ['oxygen']
Hey, what about this: "What is 'H2O' commonly called"? Water
['hey', 'what', 'about', 'this', 'what', 'is', 'h2o', 'commonly', 'called'] ['water']
Quick question: "What does 'GPU' stand for"? Graphics Processing Unit
['quick', 'question', 'what', 'does', 'gpu', 'stand', 'for'] ['graphics', 'processing', 'unit']
Hey, what about this: "Who discovered 'gravity'"? Isaac Newton
['hey', 'what', 'about', 'this', 'who', 'discovered', 'gravity'] ['isaac', 'newton']
Can you tell me, "What is a 'URL'"? Web address
['can', 'you', 'tell', 'me', 'what', 'is', 'a', 'url'] ['web', 'address']
I was wondering, "What does 'API' mean"? Application Programming Interface
['i', 'was', 'wondering', 'what', 'does', 'api', 'mean'] ['application', 'programming', 'interface']
Can you tell me, "What is 'RAM'"? Computer memory
['can', 'you', 'tell', 'me', 'what', 'is', 'ram'] ['computer', 'memory']
Can you tell me, "What is 'AI' short for"? Artificial Intelligence
['can', 'you', 'tell', 'me', 'what', 'is', 'ai', 'short', 'for'] ['artificial', 'intelligence']
Quick question: "Who wrote 'Harry Potter'"? J K Rowling
['quick', 'question', 'who', 'wrote', 'harry', 'potter'] ['j', 'k', 'rowling']
Hey, what about this: "Who discovered 'penicillin'"? Alexander Fleming
['hey', 'what', 'about', 'this', 'who', 'discovered', 'penicillin'] ['alexander', 'fleming']
Do you know, "What is 'H2O' commonly called"? Water
['do', 'you', 'know', 'what', 'is', 'h2o', 'commonly', 'called'] ['water']
Do you know, "What is 'ML' short for"? Machine Learning
['do', 'you', 'know', 'what', 'is', 'ml', 'short', 'for'] ['machine', 'learning']
I was wondering, "What is 'NLP' short for"? Natural Language Processing
['i', 'was', 'wondering', 'what', 'is', 'nlp', 'short', 'for'] ['natural', 'language', 'processing']
Do you know, "Which bird cannot fly"? Ostrich
['do', 'you', 'know', 'which', 'bird', 'cannot', 'fly'] ['ostrich']
Do you know, "Which metal is liquid at room temperature"? Mercury
['do', 'you', 'know', 'which', 'metal', 'is', 'liquid', 'at', 'room', 'temperature'] ['mercury']
"Which planet is known as the 'Red Planet'" — do you know? Mars
['which', 'planet', 'is', 'known', 'as', 'the', 'red', 'planet', 'do', 'you', 'know'] ['mars']
Hey, what about this: "Which animal is the largest on Earth"? Blue Whale
['hey', 'what', 'about', 'this', 'which', 'animal', 'is', 'the', 'largest', 'on', 'earth'] ['blue', 'whale']
"Which bird cannot fly" — do you know? Ostrich
['which', 'bird', 'cannot', 'fly', 'do', 'you', 'know'] ['ostrich']
Can you tell me, "What is 'ML' short for"? Machine Learning
['can', 'you', 'tell', 'me', 'what', 'is', 'ml', 'short', 'for'] ['machine', 'learning']
I was wondering, "What does 'CPU' stand for"? Central Processing Unit
['i', 'was', 'wondering', 'what', 'does', 'cpu', 'stand', 'for'] ['central', 'processing', 'unit']
Do you know, "What is the main religion in Saudi Arabia"? Islam
['do', 'you', 'know', 'what', 'is', 'the', 'main', 'religion', 'in', 'saudi', 'arabia'] ['islam']
Do you know, "Who wrote 'Hamlet'"? William Shakespeare
['do', 'you', 'know', 'who', 'wrote', 'hamlet'] ['william', 'shakespeare']
Can you tell me, "What is 'H2O' commonly called"? Water
['can', 'you', 'tell', 'me', 'what', 'is', 'h2o', 'commonly', 'called'] ['water']
I was wondering, "Who wrote 'Hamlet'"? William Shakespeare
['i', 'was', 'wondering', 'who', 'wrote', 'hamlet'] ['william', 'shakespeare']
Hey, what about this: "Which planet is known as the 'Red Planet'"? Mars
['hey', 'what', 'about', 'this', 'which', 'planet', 'is', 'known', 'as', 'the', 'red', 'planet'] ['mars']
"Who invented the 'light bulb'" — do you know? Thomas Edison
['who', 'invented', 'the', 'light', 'bulb', 'do', 'you', 'know'] ['thomas', 'edison']
Quick question: "What is the largest ocean"? Pacific Ocean
['quick', 'question', 'what', 'is', 'the', 'largest', 'ocean'] ['pacific', 'ocean']
Hey, what about this: "Who painted the 'Mona Lisa'"? Leonardo da Vinci

0      None
1      None
2      None
3      None
4      None
       ...
166    None
167    None
168    None
169    None
170    None
Length: 171, dtype: object

In [26]:
vocab

{'UNK': 0,
 'what': 1,
 'is': 2,
 'the': 3,
 'capital': 4,
 'of': 5,
 'france': 6,
 'paris': 7,
 'germany': 8,
 'berlin': 9,
 'italy': 10,
 'rome': 11,
 'spain': 12,
 'madrid': 13,
 'japan': 14,
 'tokyo': 15,
 'canada': 16,
 'ottawa': 17,
 'brazil': 18,
 'brasilia': 19,
 'australia': 20,
 'canberra': 21,
 'india': 22,
 'new': 23,
 'delhi': 24,
 'china': 25,
 'beijing': 26,
 'russia': 27,
 'moscow': 28,
 'united': 29,
 'states': 30,
 'washington': 31,
 'dc': 32,
 'mexico': 33,
 'city': 34,
 'egypt': 35,
 'cairo': 36,
 'turkey': 37,
 'ankara': 38,
 'argentina': 39,
 'buenos': 40,
 'aires': 41,
 'south': 42,
 'korea': 43,
 'seoul': 44,
 'indonesia': 45,
 'jakarta': 46,
 'pakistan': 47,
 'islamabad': 48,
 'bangladesh': 49,
 'dhaka': 50,
 'nepal': 51,
 'kathmandu': 52,
 'sri': 53,
 'lanka': 54,
 'colombo': 55,
 'thailand': 56,
 'bangkok': 57,
 'malaysia': 58,
 'kuala': 59,
 'lumpur': 60,
 'vietnam': 61,
 'hanoi': 62,
 'uae': 63,
 'abu': 64,
 'dhabi': 65,
 'iran': 66,
 'tehran': 67,
 'iraq': 68,
 'baghdad': 69,
 'saudi': 70,
 'arabia': 71,
 'riyadh': 72,
 'nigeria': 73,
 'abuja': 74,
 'kenya': 75,
 'nairobi': 76,
 'chile': 77,
 'santiago': 78,
 'who': 79,
 'discovered': 80,
 'gravity': 81,
 'isaac': 82,
 'newton': 83,
 'invented': 84,
 'telephone': 85,
 'alexander': 86,
 'graham': 87,
 'bell': 88,
 'h2o': 89,
 'commonly': 90,
 'called': 91,
 'water': 92,
 'which': 93,
 'gas': 94,
 'do': 95,
 'plants': 96,
 'absorb': 97,
 'carbon': 98,
 'dioxide': 99,
 'planet': 100,
 'known': 101,
 'as': 102,
 'red': 103,
 'mars': 104,
 'painted': 105,
 'mona': 106,
 'lisa': 107,
 'leonardo': 108,
 'da': 109,
 'vinci': 110,
 'largest': 111,
 'ocean': 112,
 'pacific': 113,
 'developed': 114,
 'theory': 115,
 'relativity': 116,
 'albert': 117,
 'einstein': 118,
 'ai': 119,
 'short': 120,
 'for': 121,
 'artificial': 122,
 'intelligence': 123,
 'ml': 124,
 'machine': 125,
 'learning': 126,
 'nlp': 127,
 'natural': 128,
 'language': 129,
 'processing': 130,
 'does': 131,
 'cpu': 132,
 'stand': 133,
 'central': 134,
 'unit': 135,
 'ram': 136,
 'computer': 137,
 'memory': 138,
 'gpu': 139,
 'graphics': 140,
 'a': 141,
 'url': 142,
 'web': 143,
 'address': 144,
 'http': 145,
 'hypertext': 146,
 'transfer': 147,
 'protocol': 148,
 'json': 149,
 'used': 150,
 'data': 151,
 'exchange': 152,
 'sql': 153,
 'database': 154,
 'query': 155,
 'api': 156,
 'mean': 157,
 'application': 158,
 'programming': 159,
 'interface': 160,
 'light': 161,
 'bulb': 162,
 'thomas': 163,
 'edison': 164,
 'airplane': 165,
 'wright': 166,
 'brothers': 167,
 'penicillin': 168,
 'fleming': 169,
 'wrote': 170,
 'hamlet': 171,
 'william': 172,
 'shakespeare': 173,
 'harry': 174,
 'potter': 175,
 'j': 176,
 'k': 177,
 'rowling': 178,
 'country': 179,
 'land': 180,
 'rising': 181,
 'sun': 182,
 'animal': 183,
 'king': 184,
 'jungle': 185,
 'lion': 186,
 'on': 187,
 'earth': 188,
 'blue': 189,
 'whale': 190,
 'bird': 191,
 'cannot': 192,
 'fly': 193,
 'ostrich': 194,
 'loyalty': 195,
 'dog': 196,
 'fruit': 197,
 'typically': 198,
 'apple': 199,
 'yellow': 200,
 'banana': 201,
 'organ': 202,
 'pumps': 203,
 'blood': 204,
 'heart': 205,
 'humans': 206,
 'breathe': 207,
 'oxygen': 208,
 'metal': 209,
 'liquid': 210,
 'at': 211,
 'room': 212,
 'temperature': 213,
 'mercury': 214,
 'instrument': 215,
 'measures': 216,
 'thermometer': 217,
 'pressure': 218,
 'barometer': 219,
 'main': 220,
 'portuguese': 221,
 'spanish': 222,
 'religion': 223,
 'in': 224,
 'islam': 225,
 'national': 226,
 'royal': 227,
 'bengal': 228,
 'tiger': 229,
 'quick': 230,
 'question': 231,
 'you': 232,
 'know': 233,
 'i': 234,
 'was': 235,
 'wondering': 236,
 'hey': 237,
 'about': 238,
 'this': 239,
 'can': 240,
 'tell': 241,
 'me': 242}

In [10]:
len(vocab)

243

text to indices

In [11]:
def text_to_indices(text, word_to_idx=None):
       if word_to_idx is None:
              word_to_idx = vocab

       tokens = tokenize(text) if isinstance(text, str) else text

       indexed_text=[]
       for token in tokens:
              indexed_text.append(word_to_idx.get(token, word_to_idx['UNK']))
       return indexed_text

In [12]:
text_to_indices("what is the capital of Vanuatu".split())

[1, 2, 3, 4, 5, 0]

Dataset and Dataloader

In [32]:
! pip install torch

Defaulting to user installation because normal site-packages is not writeable
Collecting torch
  Using cached torch-2.11.0-cp313-cp313-win_amd64.whl.metadata (29 kB)
Requirement already satisfied: filelock in C:\Users\Shuvo\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from torch) (3.20.3)
Requirement already satisfied: typing-extensions>=4.10.0 in C:\Users\Shuvo\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from torch) (4.15.0)
Collecting setuptools<82 (from torch)
  Using cached setuptools-81.0.0-py3-none-any.whl.metadata (6.6 kB)
Collecting sympy>=1.13.3 (from torch)
  Using cached sympy-1.14.0-py3-none-any.whl.metadata (12 kB)
Requirement already satisfied: networkx>=2.5.1 in C:\Users\Shuvo\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from torch) (3.5)
Requirement already satisfied: jinja2 in C:\Users\Shuvo\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from torch) (3.1.6)
Requirement already satisfied: fsspec>=0.8.5 in C:\Users\Shuvo\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from torch) (2026.1.0)
Collecting mpmath<1.4,>=1.1.0 (from sympy>=1.13.3->torch)
  Using cached mpmath-1.3.0-py3-none-any.whl.metadata (8.6 kB)
Requirement already satisfied: MarkupSafe>=2.0 in C:\Users\Shuvo\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from jinja2->torch) (3.0.3)
Using cached torch-2.11.0-cp313-cp313-win_amd64.whl (114.6 MB)
Using cached setuptools-81.0.0-py3-none-any.whl (1.1 MB)
Using cached sympy-1.14.0-py3-none-any.whl (6.3 MB)
Using cached mpmath-1.3.0-py3-none-any.whl (536 kB)
Installing collected packages: mpmath, sympy, setuptools, torch

   ---------------------------------------- 0/4 [mpmath]
   ---------------------------------------- 0/4 [mpmath]
   ---------------------------------------- 0/4 [mpmath]
   ---------------------------------------- 0/4 [mpmath]
   ---------------------------------------- 0/4 [mpmath]
   ---------------------------------------- 0/4 [mpmath]
   ---------------------------------------- 0/4 [mpmath]
   ---------------------------------------- 0/4 [mpmath]
   ---------------------------------------- 0/4 [mpmath]
   ---------------------------------------- 0/4 [mpmath]
   ---------- ----------------------------- 1/4 [sympy]
   ---------- ----------------------------- 1/4 [sympy]
   ---------- ----------------------------- 1/4 [sympy]
   ---------- ----------------------------- 1/4 [sympy]
   ---------- ----------------------------- 1/4 [sympy]
   ---------- ----------------------------- 1/4 [sympy]
   ---------- ----------------------------- 1/4 [sympy]
   ---------- ----------------------------- 1/4 [sympy]
   ---------- ----------------------------- 1/4 [sympy]
   ---------- ----------------------------- 1/4 [sympy]
   ---------- ----------------------------- 1/4 [sympy]
   ---------- ----------------------------- 1/4 [sympy]
   ---------- ----------------------------- 1/4 [sympy]
   ---------- ----------------------------- 1/4 [sympy]
   ---------- ----------------------------- 1/4 [sympy]
   ---------- ----------------------------- 1/4 [sympy]
   ---------- ----------------------------- 1/4 [sympy]
   ---------- ----------------------------- 1/4 [sympy]
   ---------- ----------------------------- 1/4 [sympy]
   ---------- ----------------------------- 1/4 [sympy]
   ---------- ----------------------------- 1/4 [sympy]
   ---------- ----------------------------- 1/4 [sympy]
   ---------- ----------------------------- 1/4 [sympy]
   ---------- ----------------------------- 1/4 [sympy]
   ---------- ----------------------------- 1/4 [sympy]
   ---------- ----------------------------- 1/4 [sympy]
   ---------- ----------------------------- 1/4 [sympy]
   ---------- ----------------------------- 1/4 [sympy]
   ---------- ----------------------------- 1/4 [sympy]
   ---------- ----------------------------- 1/4 [sympy]
   ---------- ----------------------------- 1/4 [sympy]
   ---------- ----------------------------- 1/4 [sympy]
   ---------- ----------------------------- 1/4 [sympy]
   ---------- ----------------------------- 1/4 [sympy]
   ---------- ----------------------------- 1/4 [sympy]
   ---------- ----------------------------- 1/4 [sympy]
   ---------- ----------------------------- 1/4 [sympy]
   ---------- ----------------------------- 1/4 [sympy]
   ---------- ----------------------------- 1/4 [sympy]
   ---------- ----------------------------- 1/4 [sympy]
   ---------- ----------------------------- 1/4 [sympy]
   ---------- ----------------------------- 1/4 [sympy]
   ---------- ----------------------------- 1/4 [sympy]
   ---------- ----------------------------- 1/4 [sympy]
   ---------- ----------------------------- 1/4 [sympy]
   ---------- ----------------------------- 1/4 [sympy]
   ---------- ----------------------------- 1/4 [sympy]
   ---------- ----------------------------- 1/4 [sympy]
   ---------- ----------------------------- 1/4 [sympy]
   ---------- ----------------------------- 1/4 [sympy]
   ---------- ----------------------------- 1/4 [sympy]
   ---------- ----------------------------- 1/4 [sympy]
   ---------- ----------------------------- 1/4 [sympy]
   ---------- ----------------------------- 1/4 [sympy]
   ---------- ----------------------------- 1/4 [sympy]
   ---------- ----------------------------- 1/4 [sympy]
   ---------- ----------------------------- 1/4 [sympy]
   ---------- ----------------------------- 1/4 [sympy]
   ---------- ----------------------------- 1/4 [sympy]
   ---------- ----------------------------- 1/4 [sympy]
   ---------- ----------------------------- 1/4 [sympy]
   ---------- ----------------------------- 1/4 [sympy]
   ---------- ----------------------------- 1/4 [sympy]
   ---------- ----------------------------- 1/4 [sympy]
   ---------- ----------------------------- 1/4 [sympy]
   ---------- ----------------------------- 1/4 [sympy]
   ---------- ----------------------------- 1/4 [sympy]
   ---------- ----------------------------- 1/4 [sympy]
   ---------- ----------------------------- 1/4 [sympy]
   ---------- ----------------------------- 1/4 [sympy]
   ---------- ----------------------------- 1/4 [sympy]
   ---------- ----------------------------- 1/4 [sympy]
   ---------- ----------------------------- 1/4 [sympy]
   ---------- ----------------------------- 1/4 [sympy]
   ---------- ----------------------------- 1/4 [sympy]
   ---------- ----------------------------- 1/4 [sympy]
   ---------- ----------------------------- 1/4 [sympy]
   ---------- ----------------------------- 1/4 [sympy]
   ---------- ----------------------------- 1/4 [sympy]
   ---------- ----------------------------- 1/4 [sympy]
   ---------- ----------------------------- 1/4 [sympy]
   ---------- ----------------------------- 1/4 [sympy]
   ---------- ----------------------------- 1/4 [sympy]
   ---------- ----------------------------- 1/4 [sympy]
   ---------- ----------------------------- 1/4 [sympy]
   ---------- ----------------------------- 1/4 [sympy]
   ---------- ----------------------------- 1/4 [sympy]
   ---------- ----------------------------- 1/4 [sympy]
   ---------- ----------------------------- 1/4 [sympy]
   ---------- ----------------------------- 1/4 [sympy]
   ---------- ----------------------------- 1/4 [sympy]
   ---------- ----------------------------- 1/4 [sympy]
   ---------- ----------------------------- 1/4 [sympy]
   ---------- ----------------------------- 1/4 [sympy]
   ---------- ----------------------------- 1/4 [sympy]
   ---------- ----------------------------- 1/4 [sympy]
   ---------- ----------------------------- 1/4 [sympy]
   ---------- ----------------------------- 1/4 [sympy]
   ---------- ----------------------------- 1/4 [sympy]
   ---------- ----------------------------- 1/4 [sympy]
   ---------- ----------------------------- 1/4 [sympy]
   ---------- ----------------------------- 1/4 [sympy]
   ---------- ----------------------------- 1/4 [sympy]
   ---------- ----------------------------- 1/4 [sympy]
   ---------- ----------------------------- 1/4 [sympy]
   ---------- ----------------------------- 1/4 [sympy]
   ---------- ----------------------------- 1/4 [sympy]
   ---------- ----------------------------- 1/4 [sympy]
   ---------- ----------------------------- 1/4 [sympy]
   ---------- ----------------------------- 1/4 [sympy]
   ---------- ----------------------------- 1/4 [sympy]
   ---------- ----------------------------- 1/4 [sympy]
   ---------- ----------------------------- 1/4 [sympy]
   ---------- ----------------------------- 1/4 [sympy]
   ---------- ----------------------------- 1/4 [sympy]
   ---------- ----------------------------- 1/4 [sympy]
   ---------- ----------------------------- 1/4 [sympy]
   ---------- ----------------------------- 1/4 [sympy]
   ---------- ----------------------------- 1/4 [sympy]
   ---------- ----------------------------- 1/4 [sympy]
   ---------- ----------------------------- 1/4 [sympy]
   ---------- ----------------------------- 1/4 [sympy]
   ---------- ----------------------------- 1/4 [sympy]
   ---------- ----------------------------- 1/4 [sympy]
   ---------- ----------------------------- 1/4 [sympy]
   ---------- ----------------------------- 1/4 [sympy]
   ---------- ----------------------------- 1/4 [sympy]
   ---------- ----------------------------- 1/4 [sympy]
   ---------- ----------------------------- 1/4 [sympy]
   ---------- ----------------------------- 1/4 [sympy]
   ---------- ----------------------------- 1/4 [sympy]
   ---------- ----------------------------- 1/4 [sympy]
   ---------- ----------------------------- 1/4 [sympy]
   ---------- ----------------------------- 1/4 [sympy]
   ---------- ----------------------------- 1/4 [sympy]
   ---------- ----------------------------- 1/4 [sympy]
   ---------- ----------------------------- 1/4 [sympy]
   ---------- ----------------------------- 1/4 [sympy]
   ---------- ----------------------------- 1/4 [sympy]
   ---------- ----------------------------- 1/4 [sympy]
   ---------- ----------------------------- 1/4 [sympy]
   ---------- ----------------------------- 1/4 [sympy]
   ---------- ----------------------------- 1/4 [sympy]
   ---------- ----------------------------- 1/4 [sympy]
   ---------- ----------------------------- 1/4 [sympy]
   ---------- ----------------------------- 1/4 [sympy]
   ---------- ----------------------------- 1/4 [sympy]
   ---------- ----------------------------- 1/4 [sympy]
   ---------- ----------------------------- 1/4 [sympy]
   ---------- ----------------------------- 1/4 [sympy]
   ---------- ----------------------------- 1/4 [sympy]
   ---------- ----------------------------- 1/4 [sympy]
   ---------- ----------------------------- 1/4 [sympy]
   ---------- ----------------------------- 1/4 [sympy]
   ---------- ----------------------------- 1/4 [sympy]
   ---------- ----------------------------- 1/4 [sympy]
   ---------- ----------------------------- 1/4 [sympy]
   ---------- ----------------------------- 1/4 [sympy]
   ---------- ----------------------------- 1/4 [sympy]
   ---------- ----------------------------- 1/4 [sympy]
   ---------- ----------------------------- 1/4 [sympy]
   ---------- ----------------------------- 1/4 [sympy]
   ---------- ----------------------------- 1/4 [sympy]
   ---------- ----------------------------- 1/4 [sympy]
   ---------- ----------------------------- 1/4 [sympy]
   ---------- ----------------------------- 1/4 [sympy]
   ---------- ----------------------------- 1/4 [sympy]
   ---------- ----------------------------- 1/4 [sympy]
   ---------- ----------------------------- 1/4 [sympy]
   ---------- ----------------------------- 1/4 [sympy]
   ---------- ----------------------------- 1/4 [sympy]
   ---------- ----------------------------- 1/4 [sympy]
   ---------- ----------------------------- 1/4 [sympy]
   ---------- ----------------------------- 1/4 [sympy]
   -------------------- ------------------- 2/4 [setuptools]
   -------------------- ------------------- 2/4 [setuptools]
   -------------------- ------------------- 2/4 [setuptools]
   -------------------- ------------------- 2/4 [setuptools]
   -------------------- ------------------- 2/4 [setuptools]
   -------------------- ------------------- 2/4 [setuptools]
   -------------------- ------------------- 2/4 [setuptools]
   -------------------- ------------------- 2/4 [setuptools]
   -------------------- ------------------- 2/4 [setuptools]
   -------------------- ------------------- 2/4 [setuptools]
   -------------------- ------------------- 2/4 [setuptools]
   -------------------- ------------------- 2/4 [setuptools]
   -------------------- ------------------- 2/4 [setuptools]
   -------------------- ------------------- 2/4 [setuptools]
   -------------------- ------------------- 2/4 [setuptools]
   -------------------- ------------------- 2/4 [setuptools]
   -------------------- ------------------- 2/4 [setuptools]
   -------------------- ------------------- 2/4 [setuptools]
   -------------------- ------------------- 2/4 [setuptools]
   -------------------- ------------------- 2/4 [setuptools]
   -------------------- ------------------- 2/4 [setuptools]
   -------------------- ------------------- 2/4 [setuptools]
   -------------------- ------------------- 2/4 [setuptools]
   -------------------- ------------------- 2/4 [setuptools]
   -------------------- ------------------- 2/4 [setuptools]
   -------------------- ------------------- 2/4 [setuptools]
   -------------------- ------------------- 2/4 [setuptools]
   -------------------- ------------------- 2/4 [setuptools]
   -------------------- ------------------- 2/4 [setuptools]
   -------------------- ------------------- 2/4 [setuptools]
   -------------------- ------------------- 2/4 [setuptools]
   -------------------- ------------------- 2/4 [setuptools]
   -------------------- ------------------- 2/4 [setuptools]
   ------------------------------ --------- 3/4 [torch]
   ------------------------------ --------- 3/4 [torch]
   ------------------------------ --------- 3/4 [torch]
   ------------------------------ --------- 3/4 [torch]
   ------------------------------ --------- 3/4 [torch]
   ------------------------------ --------- 3/4 [torch]
   ------------------------------ --------- 3/4 [torch]
   ------------------------------ --------- 3/4 [torch]
   ------------------------------ --------- 3/4 [torch]
   ------------------------------ --------- 3/4 [torch]
   ------------------------------ --------- 3/4 [torch]
   ------------------------------ --------- 3/4 [torch]
   ------------------------------ --------- 3/4 [torch]
   ------------------------------ --------- 3/4 [torch]
   ------------------------------ --------- 3/4 [torch]
   ------------------------------ --------- 3/4 [torch]
   ------------------------------ --------- 3/4 [torch]
   ------------------------------ --------- 3/4 [torch]
   ------------------------------ --------- 3/4 [torch]
   ------------------------------ --------- 3/4 [torch]
   ------------------------------ --------- 3/4 [torch]
   ------------------------------ --------- 3/4 [torch]
   ------------------------------ --------- 3/4 [torch]
   ------------------------------ --------- 3/4 [torch]
   ------------------------------ --------- 3/4 [torch]
   ------------------------------ --------- 3/4 [torch]
   ------------------------------ --------- 3/4 [torch]
   ------------------------------ --------- 3/4 [torch]
   ------------------------------ --------- 3/4 [torch]
   ------------------------------ --------- 3/4 [torch]
   ------------------------------ --------- 3/4 [torch]
   ------------------------------ --------- 3/4 [torch]
   ------------------------------ --------- 3/4 [torch]
   ------------------------------ --------- 3/4 [torch]
   ------------------------------ --------- 3/4 [torch]
   ------------------------------ --------- 3/4 [torch]
   ------------------------------ --------- 3/4 [torch]
   ------------------------------ --------- 3/4 [torch]
   ------------------------------ --------- 3/4 [torch]
   ------------------------------ --------- 3/4 [torch]
   ------------------------------ --------- 3/4 [torch]
   ------------------------------ --------- 3/4 [torch]
   ------------------------------ --------- 3/4 [torch]
   ------------------------------ --------- 3/4 [torch]
   ------------------------------ --------- 3/4 [torch]
   ------------------------------ --------- 3/4 [torch]
   ------------------------------ --------- 3/4 [torch]
   ------------------------------ --------- 3/4 [torch]
   ------------------------------ --------- 3/4 [torch]
   ------------------------------ --------- 3/4 [torch]
   ------------------------------ --------- 3/4 [torch]
   ------------------------------ --------- 3/4 [torch]
   ------------------------------ --------- 3/4 [torch]
   ------------------------------ --------- 3/4 [torch]
   ------------------------------ --------- 3/4 [torch]
   ------------------------------ --------- 3/4 [torch]
   ------------------------------ --------- 3/4 [torch]
   ------------------------------ --------- 3/4 [torch]
   ------------------------------ --------- 3/4 [torch]
   ------------------------------ --------- 3/4 [torch]
   ------------------------------ --------- 3/4 [torch]
   ------------------------------ --------- 3/4 [torch]
   ------------------------------ --------- 3/4 [torch]
   ------------------------------ --------- 3/4 [torch]
   ------------------------------ --------- 3/4 [torch]
   ------------------------------ --------- 3/4 [torch]
   ------------------------------ --------- 3/4 [torch]
   ------------------------------ --------- 3/4 [torch]
   ------------------------------ --------- 3/4 [torch]
   ------------------------------ --------- 3/4 [torch]
   ------------------------------ --------- 3/4 [torch]
   ------------------------------ --------- 3/4 [torch]
   ------------------------------ --------- 3/4 [torch]
   ------------------------------ --------- 3/4 [torch]
   ------------------------------ --------- 3/4 [torch]
   ------------------------------ --------- 3/4 [torch]
   ------------------------------ --------- 3/4 [torch]
   ------------------------------ --------- 3/4 [torch]
   ------------------------------ --------- 3/4 [torch]
   ------------------------------ --------- 3/4 [torch]
   ------------------------------ --------- 3/4 [torch]
   ------------------------------ --------- 3/4 [torch]
   ------------------------------ --------- 3/4 [torch]
   ------------------------------ --------- 3/4 [torch]
   ------------------------------ --------- 3/4 [torch]
   ------------------------------ --------- 3/4 [torch]
   ------------------------------ --------- 3/4 [torch]
   ------------------------------ --------- 3/4 [torch]
   ------------------------------ --------- 3/4 [torch]
   ------------------------------ --------- 3/4 [torch]
   ------------------------------ --------- 3/4 [torch]
   ------------------------------ --------- 3/4 [torch]
   ------------------------------ --------- 3/4 [torch]
   ------------------------------ --------- 3/4 [torch]
   ------------------------------ --------- 3/4 [torch]
   ------------------------------ --------- 3/4 [torch]
   ------------------------------ --------- 3/4 [torch]
   ------------------------------ --------- 3/4 [torch]
   ------------------------------ --------- 3/4 [torch]
   ------------------------------ --------- 3/4 [torch]

[notice] A new release of pip is available: 26.0.1 -> 26.1.1
[notice] To update, run: C:\Users\Shuvo\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip

In [13]:
import torch
from torch.utils.data import Dataset, DataLoader

In [14]:
df

                                              question   answer
0                     What is the capital of "France"?    Paris
1                    What is the capital of "Germany"?   Berlin
2                      What is the capital of "Italy"?     Rome
3                      What is the capital of "Spain"?   Madrid
4                      What is the capital of "Japan"?    Tokyo
..                                                 ...      ...
166          Can you tell me, "Which bird cannot fly"?  Ostrich
167  I was wondering, "What is 'H2O' commonly called"?    Water
168  I was wondering, "Which planet is known as the...     Mars
169  Can you tell me, "What is the main religion in...    Islam
170  Quick question: "Which animal is known for loy...      Dog

[171 rows x 2 columns]

In [62]:
df.shape[0]

171

In [63]:
index=0 
df.iloc[index]['question']

'What is the capital of "France"?'

In [64]:
index=0 
text_to_indices(tokenize(df.iloc[index]['question']))

[1, 2, 3, 4, 5, 6]

In [65]:
answer_to_idx = {answer: idx for idx, answer in enumerate(df['answer'].astype(str).str.strip().unique())}
idx_to_answer = {idx: answer for answer, idx in answer_to_idx.items()}

class QADataset(Dataset):
       def __init__(self,df,vocab,answer_to_idx):
              self.df = df
              self.vocab = vocab
              self.answer_to_idx = answer_to_idx
       def __len__(self):
              return len(self.df)
       def __getitem__(self,index):
              row = self.df.iloc[index]
              question = text_to_indices(tokenize(row['question']))
              answer = self.answer_to_idx[str(row['answer']).strip()]
              return torch.tensor(question, dtype=torch.long), torch.tensor(answer, dtype=torch.long)

In [67]:
dataset=QADataset(df,vocab,answer_to_idx)

In [68]:
dataset[1]

(tensor([1, 2, 3, 4, 5, 8]), tensor(1))

In [69]:
dataloader=DataLoader(dataset,batch_size=1,shuffle=True)

In [70]:
for question,answer in dataloader:
       print(question,answer)

tensor([[240, 232, 241, 242,  93, 215, 216, 218]]) tensor([67])
tensor([[230, 231,  79,  84,   3, 161, 162]]) tensor([51])
tensor([[237,   1, 238, 239,   1, 131, 145, 133, 121]]) tensor([47])
tensor([[234, 235, 236,  93, 179,   2, 101, 102,   3, 180,   5, 181, 182]]) tensor([56])
tensor([[ 93, 197,   2, 198, 103]]) tensor([61])
tensor([[ 93, 183,   2, 101, 121, 195]]) tensor([60])
tensor([[230, 231,  93,  94,  95,  96,  97]]) tensor([35])
tensor([[237,   1, 238, 239,  79, 105,   3, 106, 107]]) tensor([37])
tensor([[ 1,  2,  3,  4,  5, 29, 30]]) tensor([11])
tensor([[240, 232, 241, 242,  79,  84,   3, 161, 162]]) tensor([51])
tensor([[240, 232, 241, 242,   1,   2,  89,  90,  91]]) tensor([34])
tensor([[ 95, 232, 233,   1,   2, 124, 120, 121]]) tensor([41])
tensor([[  1,   2,   3, 220, 223, 224,  70,  71]]) tensor([70])
tensor([[234, 235, 236,  79,  84,   3, 165]]) tensor([52])
tensor([[79, 80, 81]]) tensor([32])
tensor([[ 1,  2,  3,  4,  5, 14]]) tensor([4])
tensor([[237,   1, 238, 239,  79, 170, 174, 175]]) tensor([55])
tensor([[ 1,  2,  3,  4,  5, 70, 71]]) tensor([28])
tensor([[230, 231,  79,  80, 168]]) tensor([53])
tensor([[ 93, 179,   2, 101, 102,   3, 180,   5, 181, 182]]) tensor([56])
tensor([[ 1,  2,  3,  4,  5, 45]]) tensor([17])
tensor([[ 1,  2,  3,  4,  5, 37]]) tensor([14])
tensor([[240, 232, 241, 242,   1,   2,   3, 220, 223, 224,  70,  71]]) tensor([70])
tensor([[234, 235, 236,  79, 170, 171]]) tensor([54])
tensor([[  1,   2, 149, 150, 121]]) tensor([48])
tensor([[240, 232, 241, 242,   1,   2, 124, 120, 121]]) tensor([41])
tensor([[230, 231,  93, 183,   2,  91,   3, 184,   5, 185]]) tensor([57])
tensor([[237,   1, 238, 239,   1,   2,   3, 111, 112]]) tensor([38])
tensor([[ 95, 232, 233,  93, 197,   2, 200]]) tensor([62])
tensor([[ 93, 215, 216, 213]]) tensor([66])
tensor([[240, 232, 241, 242,  93,  94,  95, 206, 207]]) tensor([64])
tensor([[234, 235, 236,  93, 202, 203, 204]]) tensor([63])
tensor([[237,   1, 238, 239,   1, 131, 132, 133, 121]]) tensor([43])
tensor([[ 93, 202, 203, 204]]) tensor([63])
tensor([[ 79,  84,   3,  85,  95, 232, 233]]) tensor([33])
tensor([[240, 232, 241, 242,   1, 131, 132, 133, 121]]) tensor([43])
tensor([[  1,   2,   3, 111, 112,  95, 232, 233]]) tensor([38])
tensor([[ 93, 183,   2,   3, 111, 187, 188,  95, 232, 233]]) tensor([58])
tensor([[230, 231,  93, 202, 203, 204]]) tensor([63])
tensor([[ 1,  2,  3,  4,  5, 61]]) tensor([24])
tensor([[ 93, 215, 216, 218]]) tensor([67])
tensor([[ 95, 232, 233,   1,   2, 141, 142]]) tensor([46])
tensor([[237,   1, 238, 239,  93, 183,   2,   3, 111, 187, 188]]) tensor([58])
tensor([[230, 231,  79,  84,   3,  85]]) tensor([33])
tensor([[  1,   2,   3, 226, 183,   5,  49,  95, 232, 233]]) tensor([71])
tensor([[237,   1, 238, 239,  93, 197,   2, 200]]) tensor([62])
tensor([[230, 231,  93, 179,   2, 101, 102,   3, 180,   5, 181, 182]]) tensor([56])
tensor([[ 1,  2,  3,  4,  5, 47]]) tensor([18])
tensor([[237,   1, 238, 239,  79,  84,   3,  85]]) tensor([33])
tensor([[ 79, 105,   3, 106, 107]]) tensor([37])
tensor([[ 1,  2,  3,  4,  5, 22]]) tensor([8])
tensor([[240, 232, 241, 242,  79, 170, 171]]) tensor([54])
tensor([[ 1,  2,  3,  4,  5, 18]]) tensor([6])
tensor([[234, 235, 236,   1, 131, 156, 157]]) tensor([50])
tensor([[  1, 131, 132, 133, 121]]) tensor([43])
tensor([[240, 232, 241, 242,  93, 197,   2, 200]]) tensor([62])
tensor([[ 1,  2,  3,  4,  5, 12]]) tensor([3])
tensor([[ 95, 232, 233,  79, 170, 174, 175]]) tensor([55])
tensor([[234, 235, 236,  93,  94,  95, 206, 207]]) tensor([64])
tensor([[ 1,  2,  3,  4,  5, 53, 54]]) tensor([21])
tensor([[93, 94, 95, 96, 97]]) tensor([35])
tensor([[ 79,  84,   3, 161, 162]]) tensor([51])
tensor([[ 1,  2,  3,  4,  5, 39]]) tensor([15])
tensor([[237,   1, 238, 239,  93,  94,  95,  96,  97]]) tensor([35])
tensor([[234, 235, 236,   1,   2, 127, 120, 121]]) tensor([42])
tensor([[ 1,  2,  3,  4,  5, 49]]) tensor([19])
tensor([[234, 235, 236,   1,   2, 124, 120, 121]]) tensor([41])
tensor([[ 95, 232, 233,  93, 191, 192, 193]]) tensor([59])
tensor([[  1,   2,   3, 226, 183,   5,  49]]) tensor([71])
tensor([[ 93,  94,  95, 206, 207]]) tensor([64])
tensor([[ 93, 202, 203, 204,  95, 232, 233]]) tensor([63])
tensor([[230, 231,  93, 209,   2, 210, 211, 212, 213]]) tensor([65])
tensor([[ 79, 114,   3, 115,   5, 116]]) tensor([39])
tensor([[237,   1, 238, 239,  79,  80,  81]]) tensor([32])
tensor([[ 1,  2,  3,  4,  5, 58]]) tensor([23])
tensor([[ 1,  2,  3,  4,  5, 35]]) tensor([13])
tensor([[237,   1, 238, 239,  79,  80, 168]]) tensor([53])
tensor([[ 79,  80, 168,  95, 232, 233]]) tensor([53])
tensor([[230, 231,   1,   2, 124, 120, 121]]) tensor([41])
tensor([[ 93, 191, 192, 193,  95, 232, 233]]) tensor([59])
tensor([[ 1,  2,  3,  4,  5, 51]]) tensor([20])
tensor([[ 95, 232, 233,  93,  94,  95,  96,  97]]) tensor([35])
tensor([[237,   1, 238, 239,   1,   2, 136]]) tensor([44])
tensor([[ 95, 232, 233,   1,   2,   3, 111, 112]]) tensor([38])
tensor([[ 93, 209,   2, 210, 211, 212, 213]]) tensor([65])
tensor([[240, 232, 241, 242,   1,   2, 136]]) tensor([44])
tensor([[79, 84,  3, 85]]) tensor([33])
tensor([[  1,   2,   3, 220, 129,   5,  18]]) tensor([68])
tensor([[ 93, 179,   2, 101, 102,   3, 180,   5, 181, 182,  95, 232, 233]]) tensor([56])
tensor([[ 79,  84,   3, 161, 162,  95, 232, 233]]) tensor([51])
tensor([[234, 235, 236,  79, 170, 174, 175]]) tensor([55])
tensor([[237,   1, 238, 239,   1,   2, 119, 120, 121]]) tensor([40])
tensor([[237,   1, 238, 239,   1,   2,  89,  90,  91]]) tensor([34])
tensor([[ 1,  2,  3,  4,  5, 66]]) tensor([26])
tensor([[ 95, 232, 233,   1,   2,   3, 220, 223, 224,  70,  71]]) tensor([70])
tensor([[ 95, 232, 233,   1, 131, 139, 133, 121]]) tensor([45])
tensor([[234, 235, 236,   1,   2, 136]]) tensor([44])
tensor([[ 93, 215, 216, 218,  95, 232, 233]]) tensor([67])
tensor([[ 95, 232, 233,  79,  84,   3,  85]]) tensor([33])
tensor([[  1,   2, 124, 120, 121]]) tensor([41])
tensor([[  1, 131, 139, 133, 121]]) tensor([45])
tensor([[230, 231,   1, 131, 139, 133, 121]]) tensor([45])
tensor([[  1,   2,   3, 111, 112]]) tensor([38])
tensor([[  1, 131, 145, 133, 121]]) tensor([47])
tensor([[  1,   2, 127, 120, 121]]) tensor([42])
tensor([[230, 231,  93,  94,  95, 206, 207]]) tensor([64])
tensor([[ 1,  2,  3,  4,  5, 16]]) tensor([5])
tensor([[ 93, 197,   2, 200]]) tensor([62])
tensor([[  1, 131, 156, 157]]) tensor([50])
tensor([[ 95, 232, 233,  79, 170, 171]]) tensor([54])
tensor([[  1,   2, 136]]) tensor([44])
tensor([[ 1,  2, 89, 90, 91]]) tensor([34])
tensor([[237,   1, 238, 239,   1,   2, 141, 142]]) tensor([46])
tensor([[  1,   2,   3, 220, 129,   5,  12]]) tensor([69])
tensor([[240, 232, 241, 242,  93, 191, 192, 193]]) tensor([59])
tensor([[237,   1, 238, 239,  79, 114,   3, 115,   5, 116]]) tensor([39])
tensor([[230, 231,  79, 170, 171]]) tensor([54])
tensor([[ 95, 232, 233,   1,   2,   3, 220, 129,   5,  18]]) tensor([68])
tensor([[234, 235, 236,   1, 131, 132, 133, 121]]) tensor([43])
tensor([[ 93, 183,   2,   3, 111, 187, 188]]) tensor([58])
tensor([[1, 2, 3, 4, 5, 8]]) tensor([1])
tensor([[ 95, 232, 233,  93, 179,   2, 101, 102,   3, 180,   5, 181, 182]]) tensor([56])
tensor([[ 93, 100,   2, 101, 102,   3, 103, 100,  95, 232, 233]]) tensor([36])
tensor([[237,   1, 238, 239,  93, 100,   2, 101, 102,   3, 103, 100]]) tensor([36])
tensor([[ 1,  2,  3,  4,  5, 33]]) tensor([12])
tensor([[230, 231,   1,   2,   3, 111, 112]]) tensor([38])
tensor([[ 93, 100,   2, 101, 102,   3, 103, 100]]) tensor([36])
tensor([[  1,   2, 141, 142]]) tensor([46])
tensor([[ 79, 170, 174, 175]]) tensor([55])
tensor([[234, 235, 236,  79,  84,   3, 161, 162]]) tensor([51])
tensor([[ 1,  2,  3,  4,  5, 73]]) tensor([29])
tensor([[234, 235, 236,   1,   2,  89,  90,  91]]) tensor([34])
tensor([[ 79, 170, 171]]) tensor([54])
tensor([[240, 232, 241, 242,  79,  80,  81]]) tensor([32])
tensor([[ 95, 232, 233,   1,   2,  89,  90,  91]]) tensor([34])
tensor([[1, 2, 3, 4, 5, 6]]) tensor([0])
tensor([[ 1,  2,  3,  4,  5, 27]]) tensor([10])
tensor([[230, 231,  79, 170, 174, 175]]) tensor([55])
tensor([[240, 232, 241, 242,   1,   2,   3, 226, 183,   5,  49]]) tensor([71])
tensor([[ 1,  2,  3,  4,  5, 42, 43]]) tensor([16])
tensor([[ 1,  2,  3,  4,  5, 77]]) tensor([31])
tensor([[240, 232, 241, 242,  93, 100,   2, 101, 102,   3, 103, 100]]) tensor([36])
tensor([[ 1,  2,  3,  4,  5, 63]]) tensor([25])
tensor([[ 1,  2,  3,  4,  5, 20]]) tensor([7])
tensor([[ 1,  2,  3,  4,  5, 75]]) tensor([30])
tensor([[240, 232, 241, 242,   1,   2,   3, 111, 112]]) tensor([38])
tensor([[230, 231,   1,   2,   3, 220, 129,   5,  18]]) tensor([68])
tensor([[ 79, 105,   3, 106, 107,  95, 232, 233]]) tensor([37])
tensor([[ 1,  2,  3,  4,  5, 68]]) tensor([27])
tensor([[ 79,  80, 168]]) tensor([53])
tensor([[ 1,  2,  3,  4,  5, 25]]) tensor([9])
tensor([[ 1,  2,  3,  4,  5, 10]]) tensor([2])
tensor([[  1,   2, 119, 120, 121]]) tensor([40])
tensor([[237,   1, 238, 239,  93, 215, 216, 213]]) tensor([66])
tensor([[240, 232, 241, 242,   1,   2, 119, 120, 121]]) tensor([40])
tensor([[234, 235, 236,   1,   2, 141, 142]]) tensor([46])
tensor([[  1,   2, 153]]) tensor([49])
tensor([[ 93, 183,   2,  91,   3, 184,   5, 185]]) tensor([57])
tensor([[230, 231,  93, 183,   2, 101, 121, 195]]) tensor([60])
tensor([[ 93, 191, 192, 193]]) tensor([59])
tensor([[ 95, 232, 233,  79,  84,   3, 161, 162]]) tensor([51])
tensor([[234, 235, 236,  93, 183,   2, 101, 121, 195]]) tensor([60])
tensor([[234, 235, 236,  93, 100,   2, 101, 102,   3, 103, 100]]) tensor([36])
tensor([[ 79,  84,   3, 165]]) tensor([52])
tensor([[234, 235, 236,   1,   2, 149, 150, 121]]) tensor([48])
tensor([[ 95, 232, 233,  93, 209,   2, 210, 211, 212, 213]]) tensor([65])
tensor([[230, 231,   1,   2,   3, 220, 129,   5,  12]]) tensor([69])
tensor([[240, 232, 241, 242,   1,   2, 141, 142]]) tensor([46])
tensor([[234, 235, 236,  79,  84,   3,  85]]) tensor([33])
tensor([[ 1,  2,  3,  4,  5, 56]]) tensor([22])
tensor([[237,   1, 238, 239,  93, 215, 216, 218]]) tensor([67])

sequeze

In [71]:
import torch 
x=torch.tensor([[1,2,4]])
print(x.shape)

torch.Size([1, 3])

In [72]:
y=x.squeeze()
print(y.shape)

torch.Size([3])

RNN architecture

In [73]:
import torch.nn as nn 
class simpleRNN(nn.Module):
       def __init__(self,vocab_size,answer_size,embedding_dim=50,hidden_size=64):
              super().__init__()
              self.embedding = nn.Embedding(vocab_size,embedding_dim)
              self.rnn = nn.RNN(embedding_dim,hidden_size,batch_first=True)
              self.fc=nn.Linear(hidden_size,answer_size)
       def forward(self,question):
              embedded=self.embedding(question)
              _,final=self.rnn(embedded)
              return self.fc(final.squeeze(0))

In [74]:
model=simpleRNN(vocab_size=len(vocab),answer_size=len(answer_to_idx))

In [75]:
criterion=nn.CrossEntropyLoss()
optimizer=torch.optim.Adam(model.parameters(),lr=0.001)
epochs=50

In [76]:
for epoch in range(epochs):
       total_loss = 0
       for question,answer in  dataloader:
              optimizer.zero_grad()
              output=model(question)
              loss=criterion(output,answer)
              loss.backward()
              optimizer.step()
              total_loss+=loss.item()
       if (epoch+1) % 10 == 0:
              print(f"Epoch {epoch+1}/{epochs}, Loss: {total_loss/len(dataloader):.4f}")

Epoch 10/50, Loss: 0.2055
Epoch 20/50, Loss: 0.0242
Epoch 30/50, Loss: 0.0073
Epoch 40/50, Loss: 0.0027
Epoch 50/50, Loss: 0.0011

In [77]:
vocab.items()

dict_items([('UNK', 0), ('what', 1), ('is', 2), ('the', 3), ('capital', 4), ('of', 5), ('france', 6), ('paris', 7), ('germany', 8), ('berlin', 9), ('italy', 10), ('rome', 11), ('spain', 12), ('madrid', 13), ('japan', 14), ('tokyo', 15), ('canada', 16), ('ottawa', 17), ('brazil', 18), ('brasilia', 19), ('australia', 20), ('canberra', 21), ('india', 22), ('new', 23), ('delhi', 24), ('china', 25), ('beijing', 26), ('russia', 27), ('moscow', 28), ('united', 29), ('states', 30), ('washington', 31), ('dc', 32), ('mexico', 33), ('city', 34), ('egypt', 35), ('cairo', 36), ('turkey', 37), ('ankara', 38), ('argentina', 39), ('buenos', 40), ('aires', 41), ('south', 42), ('korea', 43), ('seoul', 44), ('indonesia', 45), ('jakarta', 46), ('pakistan', 47), ('islamabad', 48), ('bangladesh', 49), ('dhaka', 50), ('nepal', 51), ('kathmandu', 52), ('sri', 53), ('lanka', 54), ('colombo', 55), ('thailand', 56), ('bangkok', 57), ('malaysia', 58), ('kuala', 59), ('lumpur', 60), ('vietnam', 61), ('hanoi', 62), ('uae', 63), ('abu', 64), ('dhabi', 65), ('iran', 66), ('tehran', 67), ('iraq', 68), ('baghdad', 69), ('saudi', 70), ('arabia', 71), ('riyadh', 72), ('nigeria', 73), ('abuja', 74), ('kenya', 75), ('nairobi', 76), ('chile', 77), ('santiago', 78), ('who', 79), ('discovered', 80), ('gravity', 81), ('isaac', 82), ('newton', 83), ('invented', 84), ('telephone', 85), ('alexander', 86), ('graham', 87), ('bell', 88), ('h2o', 89), ('commonly', 90), ('called', 91), ('water', 92), ('which', 93), ('gas', 94), ('do', 95), ('plants', 96), ('absorb', 97), ('carbon', 98), ('dioxide', 99), ('planet', 100), ('known', 101), ('as', 102), ('red', 103), ('mars', 104), ('painted', 105), ('mona', 106), ('lisa', 107), ('leonardo', 108), ('da', 109), ('vinci', 110), ('largest', 111), ('ocean', 112), ('pacific', 113), ('developed', 114), ('theory', 115), ('relativity', 116), ('albert', 117), ('einstein', 118), ('ai', 119), ('short', 120), ('for', 121), ('artificial', 122), ('intelligence', 123), ('ml', 124), ('machine', 125), ('learning', 126), ('nlp', 127), ('natural', 128), ('language', 129), ('processing', 130), ('does', 131), ('cpu', 132), ('stand', 133), ('central', 134), ('unit', 135), ('ram', 136), ('computer', 137), ('memory', 138), ('gpu', 139), ('graphics', 140), ('a', 141), ('url', 142), ('web', 143), ('address', 144), ('http', 145), ('hypertext', 146), ('transfer', 147), ('protocol', 148), ('json', 149), ('used', 150), ('data', 151), ('exchange', 152), ('sql', 153), ('database', 154), ('query', 155), ('api', 156), ('mean', 157), ('application', 158), ('programming', 159), ('interface', 160), ('light', 161), ('bulb', 162), ('thomas', 163), ('edison', 164), ('airplane', 165), ('wright', 166), ('brothers', 167), ('penicillin', 168), ('fleming', 169), ('wrote', 170), ('hamlet', 171), ('william', 172), ('shakespeare', 173), ('harry', 174), ('potter', 175), ('j', 176), ('k', 177), ('rowling', 178), ('country', 179), ('land', 180), ('rising', 181), ('sun', 182), ('animal', 183), ('king', 184), ('jungle', 185), ('lion', 186), ('on', 187), ('earth', 188), ('blue', 189), ('whale', 190), ('bird', 191), ('cannot', 192), ('fly', 193), ('ostrich', 194), ('loyalty', 195), ('dog', 196), ('fruit', 197), ('typically', 198), ('apple', 199), ('yellow', 200), ('banana', 201), ('organ', 202), ('pumps', 203), ('blood', 204), ('heart', 205), ('humans', 206), ('breathe', 207), ('oxygen', 208), ('metal', 209), ('liquid', 210), ('at', 211), ('room', 212), ('temperature', 213), ('mercury', 214), ('instrument', 215), ('measures', 216), ('thermometer', 217), ('pressure', 218), ('barometer', 219), ('main', 220), ('portuguese', 221), ('spanish', 222), ('religion', 223), ('in', 224), ('islam', 225), ('national', 226), ('royal', 227), ('bengal', 228), ('tiger', 229), ('quick', 230), ('question', 231), ('you', 232), ('know', 233), ('i', 234), ('was', 235), ('wondering', 236), ('hey', 237), ('about', 238), ('this', 239), ('can', 240), ('tell', 241), ('me', 242)])

In [79]:
idx_to_word={idx: word for word, idx in vocab.items()}
idx_to_word

{0: 'UNK',
 1: 'what',
 2: 'is',
 3: 'the',
 4: 'capital',
 5: 'of',
 6: 'france',
 7: 'paris',
 8: 'germany',
 9: 'berlin',
 10: 'italy',
 11: 'rome',
 12: 'spain',
 13: 'madrid',
 14: 'japan',
 15: 'tokyo',
 16: 'canada',
 17: 'ottawa',
 18: 'brazil',
 19: 'brasilia',
 20: 'australia',
 21: 'canberra',
 22: 'india',
 23: 'new',
 24: 'delhi',
 25: 'china',
 26: 'beijing',
 27: 'russia',
 28: 'moscow',
 29: 'united',
 30: 'states',
 31: 'washington',
 32: 'dc',
 33: 'mexico',
 34: 'city',
 35: 'egypt',
 36: 'cairo',
 37: 'turkey',
 38: 'ankara',
 39: 'argentina',
 40: 'buenos',
 41: 'aires',
 42: 'south',
 43: 'korea',
 44: 'seoul',
 45: 'indonesia',
 46: 'jakarta',
 47: 'pakistan',
 48: 'islamabad',
 49: 'bangladesh',
 50: 'dhaka',
 51: 'nepal',
 52: 'kathmandu',
 53: 'sri',
 54: 'lanka',
 55: 'colombo',
 56: 'thailand',
 57: 'bangkok',
 58: 'malaysia',
 59: 'kuala',
 60: 'lumpur',
 61: 'vietnam',
 62: 'hanoi',
 63: 'uae',
 64: 'abu',
 65: 'dhabi',
 66: 'iran',
 67: 'tehran',
 68: 'iraq',
 69: 'baghdad',
 70: 'saudi',
 71: 'arabia',
 72: 'riyadh',
 73: 'nigeria',
 74: 'abuja',
 75: 'kenya',
 76: 'nairobi',
 77: 'chile',
 78: 'santiago',
 79: 'who',
 80: 'discovered',
 81: 'gravity',
 82: 'isaac',
 83: 'newton',
 84: 'invented',
 85: 'telephone',
 86: 'alexander',
 87: 'graham',
 88: 'bell',
 89: 'h2o',
 90: 'commonly',
 91: 'called',
 92: 'water',
 93: 'which',
 94: 'gas',
 95: 'do',
 96: 'plants',
 97: 'absorb',
 98: 'carbon',
 99: 'dioxide',
 100: 'planet',
 101: 'known',
 102: 'as',
 103: 'red',
 104: 'mars',
 105: 'painted',
 106: 'mona',
 107: 'lisa',
 108: 'leonardo',
 109: 'da',
 110: 'vinci',
 111: 'largest',
 112: 'ocean',
 113: 'pacific',
 114: 'developed',
 115: 'theory',
 116: 'relativity',
 117: 'albert',
 118: 'einstein',
 119: 'ai',
 120: 'short',
 121: 'for',
 122: 'artificial',
 123: 'intelligence',
 124: 'ml',
 125: 'machine',
 126: 'learning',
 127: 'nlp',
 128: 'natural',
 129: 'language',
 130: 'processing',
 131: 'does',
 132: 'cpu',
 133: 'stand',
 134: 'central',
 135: 'unit',
 136: 'ram',
 137: 'computer',
 138: 'memory',
 139: 'gpu',
 140: 'graphics',
 141: 'a',
 142: 'url',
 143: 'web',
 144: 'address',
 145: 'http',
 146: 'hypertext',
 147: 'transfer',
 148: 'protocol',
 149: 'json',
 150: 'used',
 151: 'data',
 152: 'exchange',
 153: 'sql',
 154: 'database',
 155: 'query',
 156: 'api',
 157: 'mean',
 158: 'application',
 159: 'programming',
 160: 'interface',
 161: 'light',
 162: 'bulb',
 163: 'thomas',
 164: 'edison',
 165: 'airplane',
 166: 'wright',
 167: 'brothers',
 168: 'penicillin',
 169: 'fleming',
 170: 'wrote',
 171: 'hamlet',
 172: 'william',
 173: 'shakespeare',
 174: 'harry',
 175: 'potter',
 176: 'j',
 177: 'k',
 178: 'rowling',
 179: 'country',
 180: 'land',
 181: 'rising',
 182: 'sun',
 183: 'animal',
 184: 'king',
 185: 'jungle',
 186: 'lion',
 187: 'on',
 188: 'earth',
 189: 'blue',
 190: 'whale',
 191: 'bird',
 192: 'cannot',
 193: 'fly',
 194: 'ostrich',
 195: 'loyalty',
 196: 'dog',
 197: 'fruit',
 198: 'typically',
 199: 'apple',
 200: 'yellow',
 201: 'banana',
 202: 'organ',
 203: 'pumps',
 204: 'blood',
 205: 'heart',
 206: 'humans',
 207: 'breathe',
 208: 'oxygen',
 209: 'metal',
 210: 'liquid',
 211: 'at',
 212: 'room',
 213: 'temperature',
 214: 'mercury',
 215: 'instrument',
 216: 'measures',
 217: 'thermometer',
 218: 'pressure',
 219: 'barometer',
 220: 'main',
 221: 'portuguese',
 222: 'spanish',
 223: 'religion',
 224: 'in',
 225: 'islam',
 226: 'national',
 227: 'royal',
 228: 'bengal',
 229: 'tiger',
 230: 'quick',
 231: 'question',
 232: 'you',
 233: 'know',
 234: 'i',
 235: 'was',
 236: 'wondering',
 237: 'hey',
 238: 'about',
 239: 'this',
 240: 'can',
 241: 'tell',
 242: 'me'}

In [83]:
def predict(question_text,vocab,model,idx_to_answer):
       model.eval()
       with torch.no_grad():
              indices=text_to_indices(question_text, vocab)
              if not indices:
                     return "<UNK>"
              x=torch.tensor(indices, dtype=torch.long).unsqueeze(0)
              pred=torch.argmax(model(x),dim=1).item()
              return idx_to_answer.get(pred,"<UNK>")

In [84]:
tests=[
       "What is the capital of France?",
       "Who is the president of the United States?",
       "What is the largest mammal?",]
for test in tests:
       answer=predict(test,vocab,model,idx_to_word)
       print(f"Q: {test}\nA: {answer}\n")

Q: What is the capital of France?
A: UNK

Q: Who is the president of the United States?
A: rome

Q: What is the largest mammal?
A: ankara